name: Deploy to EKS

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t your-repo-name:latest .
          docker tag your-repo-name:latest your-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:latest
          docker push your-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:latest

      - name: Set up kubectl
        uses: aws-actions/eks-set-kubeconfig@v1
        with:
          cluster-name: your-cluster-name
          region: us-east-1

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

